{
 "title": "custom",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Disk Usage - HAproxy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\", instance=\"192.168.68.91:9100\"} - node_filesystem_avail_bytes{mountpoint=\"/\", instance=\"192.168.68.91:9100\"}) / node_filesystem_size_bytes{mountpoint=\"/\", instance=\"192.168.68.91:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Usage - HAproxy",
   "type": "gauge",
   "description": "\n",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (node_memory_MemTotal_bytes{instance=\"192.168.68.91:9100\", job=\"node_exporter\"} - node_memory_MemAvailable_bytes{instance=\"192.168.68.91:9100\", job=\"node_exporter\"}) / sum by (instance) (node_memory_MemTotal_bytes{instance=\"192.168.68.91:9100\", job=\"node_exporter\"})) * 100\r\n",
     "legendFormat": "HAproxy"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"192.168.68.91:9100\"} - node_boot_time_seconds{instance=\"192.168.68.91:9100\"}",
     "legendFormat": "HAproxy"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.68.92:9100\"} - node_boot_time_seconds{instance=\"192.168.68.92:9100\"}",
     "legendFormat": "node2"
    },
    {
     "expr": "node_time_seconds{instance=\"192.168.68.93:9100\"} - node_boot_time_seconds{instance=\"192.168.68.93:9100\"}",
     "legendFormat": "node3"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "\n",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Backend Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_backend_active_servers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage - HAproxy",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.68.91:9100\", job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / sum by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.68.91:9100\", job=\"node_exporter\"}[$__rate_interval])) * 100",
     "legendFormat": "node1.streetrack.org"
    }
   ]
  },
  {
   "title": "CPU Usage - Webservers",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.68.92:9100\", job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / sum by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.68.92:9100\", job=\"node_exporter\"}[$__rate_interval])) * 100",
     "legendFormat": "node2.streetrack.org"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.68.93:9100\", job=\"node_exporter\", mode!=\"idle\"}[$__rate_interval])) / sum by (instance) (irate(node_cpu_seconds_total{instance=\"192.168.68.93:9100\", job=\"node_exporter\"}[$__rate_interval])) * 100",
     "legendFormat": "node3.streetrack.org"
    }
   ]
  },
  {
   "title": "Load Average - HAproxy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=\"192.168.68.91:9100\"}",
     "legendFormat": "Load 1m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load5{instance=\"192.168.68.91:9100\"}",
     "legendFormat": "Load 5m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load5%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load15{instance=\"192.168.68.91:9100\"}",
     "legendFormat": "Load 15m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load15%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Load Average - Webservers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=\"192.168.68.92:9100\"}",
     "legendFormat": "node2.streetrack.org Load 1m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=\"192.168.68.93:9100\"}",
     "legendFormat": "node3.streetrack.org Load 1m",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load5%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Traffic - HAproxy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes_total{instance=\"192.168.68.91:9100\", device!=\"lo\"}[$__interval]) or irate(node_network_receive_bytes_total{instance=\"192.168.68.91:9100\", device!=\"lo\"}[$__rate_interval])",
     "legendFormat": "Inbound",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{instance=\"192.168.68.91:9100\", device!=\"lo\"}[$__interval]) or irate(node_network_transmit_bytes_total{instance=\"192.168.68.91:9100\", device!=\"lo\"}[$__rate_interval])",
     "legendFormat": "Outbound",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Memory Usage - Webservers",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (instance) (node_memory_MemTotal_bytes{instance=\"192.168.68.92:9100\", job=\"node_exporter\"} - node_memory_MemAvailable_bytes{instance=\"192.168.68.92:9100\", job=\"node_exporter\"}) / sum by (instance) (node_memory_MemTotal_bytes{instance=\"192.168.68.92:9100\", job=\"node_exporter\"})) * 100\r\n",
     "legendFormat": "node2.streetrack.org"
    },
    {
     "expr": "(sum by (instance) (node_memory_MemTotal_bytes{instance=\"192.168.68.93:9100\", job=\"node_exporter\"} - node_memory_MemAvailable_bytes{instance=\"192.168.68.93:9100\", job=\"node_exporter\"}) / sum by (instance) (node_memory_MemTotal_bytes{instance=\"192.168.68.93:9100\", job=\"node_exporter\"})) * 100\r\n\r\n",
     "legendFormat": "node3.streetrack.org"
    }
   ]
  },
  {
   "title": "HTTP Request Rate - HAproxy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "irate(haproxy_frontend_http_requests_total{instance=\"192.168.68.91:8405\", job=\"haproxy_metrics\", proxy=\"load_balancer\"}[$__rate_interval])",
     "legendFormat": "node1.streetrack.org",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Session Rate - Webservers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(haproxy_server_sessions_total{proxy=\"webservers\",server=\"node2\"}[$__rate_interval])",
     "legendFormat": "node2.streetrack.org",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "rate(haproxy_server_sessions_total{proxy=\"webservers\",server=\"node3\"}[$__rate_interval])",
     "legendFormat": "node3.streetrack.org"
    }
   ]
  },
  {
   "title": "HAproxy - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"haproxy\"} |= ``"
    }
   ]
  },
  {
   "title": "Security - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{job=\"secure\"}"
    }
   ]
  },
  {
   "title": "General - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{job=\"messages\"} |= ``"
    }
   ]
  },
  {
   "title": "Apache Error - Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/httpd/error_log\"}"
    }
   ]
  }
 ]
}