---
- name: install and configure webserver
  hosts: webservers
  roles:
    - webserver

- name: install and configure haproxy loadbalancer
  hosts: balancers
  roles:
    - loadbalancer

- name: install and configure grafana
  hosts: localhost
  roles:
    - grafana

- name: wait for connection
  hosts: balancers webservers
  tasks:
  - name: Wait for systems to become reachable
    wait_for_connection:

- name: install and configure node_exporter
  hosts: balancers webservers
  roles:
    - node_exporter

- name: install and configure prometheus
  hosts: localhost
  roles:
    - prometheus

- name: install and configure promtail
  hosts: balancers webservers
  roles:
    - promtail

- name: install and configure loki
  hosts: localhost
  roles:
    - loki

- name: install and configure alertmanager
  hosts: localhost
  roles:
    - alertmanager
