---
- name: download and unarchive alertmanager
  unarchive:
    src: 'https://github.com/prometheus/alertmanager/releases/download/v0.27.0/alertmanager-0.27.0.linux-amd64.tar.gz'
    dest: /home/ansible/ha_webtrack/
    remote_src: true
- name: copy executables
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    mode: '0750'
  loop:
    - alertmanager-0.27.0.linux-amd64/alertmanager
    - alertmanager-0.27.0.linux-amd64/amtool
- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/alertmanager
    - /var/lib/alertmanager
- name: j2
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
    owner: prometheus
    group: prometheus
  loop: "{{ jinja }}"
  tags: j2
- name: run service template
  template:
    src: alertmanager_service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: '0640'
- name: selinux port open
  seport:
    ports: 9093
    proto: tcp
    setype: http_port_t
    state: present
- name: open port 9090 in firewalld
  firewalld:
    port: 9093/tcp
    permanent: true
    state: enabled
- name: reload systemd
  shell: 'systemctl daemon-reload'
- name: start and enable alertmanager and prometheus
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - firewalld
    - alertmanager
    - prometheus



