- name: download and unarchive node_exporter
  unarchive:
    src: 'https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz'
    dest: /home/ansible/
    remote_src: true
- name: create node_exporter group
  group:
    name: node_exporter
    state: present
- name: create node_exporter user
  user:
    name: node_exporter
    shell: /usr/bin/false
    group: node_exporter
    create_home: false
    system: true
- name: copy executable 
  copy:
    src: /home/ansible/node_exporter-1.8.2.linux-amd64/node_exporter
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: true
- name: run service template
  template:
    src: node_exporter.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
- name: selinux port open 9100 with http_port_t type
  seport:
    ports: 9100
    proto: tcp
    setype: http_port_t
    state: present
- name: open port 9100 in firewalld
  firewalld:
    port: 9100/tcp
    permanent: true
    state: enabled
- name: restart firewalld
  service:
    name: firewalld
    state: restarted
- name: reload systemd
  shell: 'systemctl daemon-reload'
- name: start and enable node-exporter
  service:
    name: node_exporter
    state: restarted
    enabled: true
